### ISSUE TITLE
Links para páginas do acervo de projetos retornam erro 404

### ISSUE THREAD

**Issue by BrianMunizSilveira** [Allan-Carlos/Templates#2]
Olá, tudo certo por ai @Allan-Neves ?,

Identifiquei que alguns links no acervo de projetos estão com problemas e não estão funcionando corretamente. Isso está impactando a capacidade de acessar as páginas específicas dos projetos.

Os links até a seção 'Top Links' estão funcionando corretamente, porém a partir da seção 'Social Links' até 'Photography' está retornando erro 404.

**Passos para reproduzir o problema:**

1. Acesse o acervo de projetos em: [Templates](https://projetosallan.vercel.app/).
2. Navegue até a seção 'Social Links' e clique no link do projeto 'Social Links'.
3. Observe que a página retorna erro 404.

**Capturas de tela / Logs:**

- ![Social Links: erro 404](https://i.imgur.com/au46Tyt.png)
- ![Churrascômetro: erro 404](https://i.imgur.com/3od1jhK.png)

**Comportamento esperado:**

Os links devem redirecionar corretamente para as páginas dos projetos correspondentes.

**Comportamento atual:**

Os links retornam erro 404 e levam a páginas não encontradas.

**Informações adicionais:**

- Navegador utilizado: Brave, V 1.69.160
- Sistema operacional: Windows 10 Home, 22H2

Agradeço a atenção e espero que o problema seja resolvido, estou curioso para ver estes projetos.

**Comment by Allan-Neves** [comment]
Bom dia, @BrianMunizSilveira ! Como vai? Obrigado pelo alerta. Mudei meu usuário no github e acabei esqeucendo de atualizar. Correção feita.
